export const MOCK_GENERATED_CODE = `
<!-- 
  GENERATED BY QUANTUM DEVSTUDIO 
  MODEL: GEMINI-2.5-FLASH 
-->
<div class="min-h-screen bg-slate-900 text-white font-sans">
  <!-- Navbar -->
  <nav class="sticky top-0 z-50 border-b border-slate-800 bg-slate-900/90 backdrop-blur-md">
    <div class="container mx-auto px-6 py-4 flex justify-between items-center">
      <div class="text-2xl font-bold tracking-tighter text-cyan-400">
        CYBER<span class="text-white">KICKS</span>
      </div>
      <div class="hidden md:flex space-x-8 text-sm font-medium text-slate-300">
        <a href="#" class="hover:text-cyan-400 transition-colors">New Arrivals</a>
        <a href="#" class="hover:text-cyan-400 transition-colors">Collections</a>
        <a href="#" class="hover:text-cyan-400 transition-colors">Custom Lab</a>
      </div>
      <button class="bg-cyan-500 hover:bg-cyan-400 text-black font-bold py-2 px-6 rounded-full transition-all shadow-[0_0_15px_rgba(6,182,212,0.5)]">
        Cart (0)
      </button>
    </div>
  </nav>

  <!-- Hero Section -->
  <header class="relative pt-20 pb-32 overflow-hidden">
    <div class="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-cyan-900/20 via-slate-900 to-slate-900"></div>
    <div class="container mx-auto px-6 relative z-10 text-center">
      <span class="inline-block py-1 px-3 rounded-full bg-slate-800 border border-slate-700 text-cyan-400 text-xs font-mono mb-6">
        LIMITED EDITION DROP: NEON SERIES
      </span>
      <h1 class="text-6xl md:text-8xl font-extrabold tracking-tight mb-8 bg-clip-text text-transparent bg-gradient-to-b from-white to-slate-500">
        STEP INTO THE <br/><span class="text-cyan-400">FUTURE</span>
      </h1>
      <p class="text-lg text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
        Engineered for the urban nomad. Featuring self-lacing tech and bioluminescent soles. 
        Experience the next evolution of footwear.
      </p>
      <div class="flex flex-col md:flex-row justify-center gap-4">
        <button class="bg-white text-black hover:bg-slate-200 font-bold py-4 px-10 rounded-full transition-transform hover:scale-105">
          Shop Collection
        </button>
        <button class="border border-slate-700 hover:border-cyan-400 text-white font-bold py-4 px-10 rounded-full transition-colors bg-slate-900/50 backdrop-blur">
          View Lookbook
        </button>
      </div>
    </div>
  </header>

  <!-- Product Grid -->
  <section class="py-20 bg-slate-950">
    <div class="container mx-auto px-6">
      <div class="flex justify-between items-end mb-12">
        <h2 class="text-3xl font-bold">Trending Now</h2>
        <a href="#" class="text-cyan-400 hover:underline font-mono text-sm">VIEW ALL -></a>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <!-- Card 1 -->
        <div class="group relative bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 hover:border-cyan-500/50 transition-all duration-300">
          <div class="aspect-square bg-slate-800 relative overflow-hidden">
             <img src="https://picsum.photos/600/600?random=1" alt="Shoe" class="object-cover w-full h-full group-hover:scale-110 transition-transform duration-700 opacity-80 group-hover:opacity-100" />
             <div class="absolute top-4 right-4 bg-black/50 backdrop-blur px-2 py-1 rounded text-xs font-mono text-white">NEW</div>
          </div>
          <div class="p-6">
            <h3 class="text-xl font-bold mb-2">Vector Runner X1</h3>
            <p class="text-slate-400 text-sm mb-4">Cyber-green mesh with reactive cushioning.</p>
            <div class="flex justify-between items-center">
              <span class="text-cyan-400 font-mono text-lg">$189.00</span>
              <button class="p-2 bg-white text-black rounded-full hover:bg-cyan-400 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
              </button>
            </div>
          </div>
        </div>

         <!-- Card 2 -->
        <div class="group relative bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 hover:border-cyan-500/50 transition-all duration-300">
          <div class="aspect-square bg-slate-800 relative overflow-hidden">
             <img src="https://picsum.photos/600/600?random=2" alt="Shoe" class="object-cover w-full h-full group-hover:scale-110 transition-transform duration-700 opacity-80 group-hover:opacity-100" />
          </div>
          <div class="p-6">
            <h3 class="text-xl font-bold mb-2">Void Walker Z</h3>
            <p class="text-slate-400 text-sm mb-4">Stealth black edition. Waterproof polymer.</p>
            <div class="flex justify-between items-center">
              <span class="text-cyan-400 font-mono text-lg">$245.00</span>
               <button class="p-2 bg-white text-black rounded-full hover:bg-cyan-400 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
              </button>
            </div>
          </div>
        </div>

         <!-- Card 3 -->
        <div class="group relative bg-slate-900 rounded-2xl overflow-hidden border border-slate-800 hover:border-cyan-500/50 transition-all duration-300">
          <div class="aspect-square bg-slate-800 relative overflow-hidden">
             <img src="https://picsum.photos/600/600?random=3" alt="Shoe" class="object-cover w-full h-full group-hover:scale-110 transition-transform duration-700 opacity-80 group-hover:opacity-100" />
          </div>
          <div class="p-6">
            <h3 class="text-xl font-bold mb-2">Glitch High-Tops</h3>
            <p class="text-slate-400 text-sm mb-4">Limited glitch art canvas print.</p>
            <div class="flex justify-between items-center">
              <span class="text-cyan-400 font-mono text-lg">$159.00</span>
               <button class="p-2 bg-white text-black rounded-full hover:bg-cyan-400 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
`;

export const INITIAL_CODE_STATE = `<!-- 
  Welcome to Quantum DevStudio
  Your generated code will appear here.
  
  Start by entering a prompt in the Control Center.
-->
<div class="h-full flex items-center justify-center bg-slate-950 text-slate-500 font-mono">
  <div class="text-center">
    <p class="text-xl mb-2">Awaiting Input Signal...</p>
    <p class="text-sm opacity-50">System Standby</p>
  </div>
</div>`;